# Generated by Django 3.0.7 on 2020-06-17 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_userconnection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('follower', 'followee')},
        ),
    ]
